const BRANDS_BY_LETTER: Record<string, string[]> = {
  A: ['A. Mostes','AB Yachts','Abacus','Abeking & Rasmussen','Absolute','ACM Dufour','Adagio Yachts','Adventure','Agder','Aicon','Airon Marine','AKA Marine','Albin','Alfastreet','Allroundmarin','Altena','Alubat','AluShip','Amel','American Marine','AMT','Antaris','Apreamare','Aquador','Aqualine','Aquanaut','Aquaspirit','Archambault','Arcoa','Arcona','Arvor','AS Marine','Askeladden','Astondoa','Atlantic','Atlantis','Aventura Catamarans','Axopar','Azimut'],
  B: ['B2 Marine','Baia','Baja','Bali Catamarans','Balt Yacht','Baltic','Bandholm','Barkas','Bavaria','Bayliner','Bella','Benetti','Bénéteau','Bente','Bertram','Bianca','Bianca Yachts','Birchwood','BlueCraft','Bluegame','BMA','Boesch','Bombard','Boston Whaler','Botnia Marin','Brabus','Brandsma','Brenderup','Brig','Broom','Bruce Roberts','Bruno Abbate','BSC','Bucher','Buster','BWA'],
  C: ['Caminada','CampiBoat','Campion','Canados','Cantieri di Pisa','Cantieri di Sarnico','Cantieri Estensi','Capelli','Capoforte','Caravelle','Carnevali','Carver','Cascaruda','Catalina','Catana','Cayman','Celebrity','Centurion','Chaparral','Chris Craft','Cigarette','Classic','Clever','CNB','Coaster','Cobalt','Cobra Yachts','Cobrey','Colin Archer','Colombo','Colvic','Comar','Comfortina','Comitti','Compromis','Conam','Concordia','Contest','Conyplex','Cormate','Coronet','Correct Craft','Corsiva','Cranchi','Cremo','Crescent','Crownline','Cruisers Yachts','Cytra'],
  D: ['DarekCo','De Antonio Yachts','De Boarnstream','Deerberg','Dehler','Dellapasqua','Delphia','Delta Powerboats','Doerak','Doggersbank','Dominator','Donzi','Doqueve','Doral','Draco','Drago Boats','Dragonfly','DSB','Dufour'],
  E: ['Edership','Elan','Elegance','Elling','Emka','Enterprise Marine','Eolo','Epropulsion','Esse','Etap','Excellent','Excess'],
  F: ['Faeton','Fairline','Falcon','Fareast','Farr','Fashion Yachts','Feadship','Feltz','Ferretti','Fiart Mare','Fiberline','Fibrafort','FIM','Finnmaster','Finval','Fjord','Fjordjollen','Fletcher','Flipper','Flying Shark','Focus Motor Yacht','Formosa','Formula','Fountaine Pajot','Four Winns','Frauscher','Friendship','Friendship Yacht Company','Futuro','Füllemann'],
  G: ['Gagliotta','GALA','Galeon','Galia','Gelex','Gib Sea','Gillissen','Glastron','Gobbi','Grady White Boats','Granada','Grand','Grand Banks','Grand Marine','Grand Soleil','Grandezza','Greenline','Gruno','Guy Couach'],
  H: ['Hallberg-Rassy','Hanse','Harbeck','Haswing Marine','Hatteras','Heinrich','Hellwig','Highfield','Hollandia','Honda','Honda Honwave','Horizon','Hunter','Hydrolift','Hydrosport'],
  I: ['Ibiza Boats','ICE Yachts','Idea Marine','Ijlstervlet','Ilver','Innovazione & Progetti','Inter Trading A/S','Interboat','Interboat DE','Intermare','Invader','Invictus','IRON','Italboats','Italia Yachts'],
  J: ['J Boats','Jan Van Gent','Jeanneau','Joda','Joker Boat','Jongert'],
  K: ['Karel','Karnic','Kimple','Kirie','Kolibri','Koopmans'],
  L: ['La Mare','Lago Amore','Lagoon','Larson','Lema','Lemsteraak','Leopard','Linder','Linssen','LM','Lomac','Luhrs'],
  M: ['Maiora','Makma','Malibu','Malö Yachts','Mangusta','Manò Marine','Marex','Mariah','Marian','Maril','Marine','Marine Projects','Marinello','Marion','Marlin','Martz','MasterCraft','Maxi','Maxima','Maxum','Mazuria','Mändli','Menorquin','MerCruiser','Mercury','Meridian Yachts','Mingolla','Mirakul','Mochi Craft','Monachus','Monte Carlo Yachts','Monterey','Moody','Moomba','More','Mulder'],
  N: ['Najad','Nautica','Nauticat','Nautique','Nautitech',"Nautor's Swan",'Navan','Neel','Neptun','Neptunus','Nicols Yacht','Nidelv','Nimarine','Nimbus'],
  O: ['Ocean Alexander','Ocqueteau','Omega Marine','Opal','Orkney','Orion','Outboard Marine','Ovation'],
  P: ['Pacific','Palm Beach','Parker','Pardo','Pathfinder','Pearlsea','Pershing','Phantom','Phoenix','Pioneer','Pirelli','Polaris','Poseidon','Prestige','Princess','Pro-Line'],
  Q: ['Quicksilver'],
  R: ['Regal','Regent','Riva','Riviera','Robalo','Robin Hood','Rodriguez','Rossmann','Ryds'],
  S: ['Saga','Sargo','Scout','Sea Ray','Sea Spirit','Sealine','Sessa Marine','Sialia','Skipper','Stingher','Storebro','Sunbeam','Sunbird','Suncraft','Sunseeker'],
  T: ['Tarpon','Tempest','Tiara','Tiger Marine','Tofinou','Topaz','Tracker','Trophy','True North'],
  U: ['Uniesse','Uttern'],
  V: ['Valiant','Vanquish','Victory','Viking','Vilm','Vitech'],
  W: ['Wellcraft','Westerly','Whittley','Winner','Windy'],
  X: ['X-Yachts','XO Boats'],
  Y: ['Yamarin','Yareti'],
  Z: ['Zodiac'],
};

export const ALL_BOAT_BRANDS: string[] = Object.values(BRANDS_BY_LETTER).flat().sort((a, b) => a.localeCompare(b, 'de'));
